In [ ]:
import tensorflow as tf
import os
import platform

print("TensorFlow version:", tf.__version__)

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

tf.debugging.set_log_device_placement(True)
tf.config.run_functions_eagerly(False)
print(tf.config.list_physical_devices())

print(tf.config.list_physical_devices('GPU'))

In [29]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.5609575 , -0.02706783,  0.27855206, -0.02784897,  0.79859716,
         0.4704686 , -0.03770313, -0.07783635, -0.10525171,  0.33428743]],
      dtype=float32)

In [30]:
tf.nn.softmax(predictions).numpy()

array([[0.13450933, 0.07470956, 0.10141572, 0.07465123, 0.17059173,
        0.12287217, 0.07391922, 0.07101135, 0.06909098, 0.10722864]],
      dtype=float32)

In [31]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.0966105

In [32]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [33]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 626us/step - loss: 0.2967 - accuracy: 0.9138
Epoch 2/5
1875/1875 [==============================] - 1s 604us/step - loss: 0.1429 - accuracy: 0.9567
Epoch 3/5
1875/1875 [==============================] - 1s 604us/step - loss: 0.1069 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 1s 608us/step - loss: 0.0881 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 1s 594us/step - loss: 0.0754 - accuracy: 0.9764


In [34]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 0s - loss: 0.0763 - accuracy: 0.9765 - 142ms/epoch - 452us/step


[0.07625996321439743, 0.9764999747276306]

In [35]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [36]:
probability_model(x_test[:5])


<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.42398990e-09, 2.46972292e-07, 3.05372596e-05, 2.14473534e-04,
        2.01067274e-10, 1.21183765e-08, 5.32731750e-14, 9.99753535e-01,
        6.36020587e-08, 1.11584268e-06],
       [1.16772036e-09, 1.62268654e-04, 9.99826491e-01, 4.95744735e-06,
        6.18500607e-12, 3.13638111e-07, 2.68529421e-09, 4.36832509e-13,
        5.95839037e-06, 1.07151214e-15],
       [1.85353457e-07, 9.98745799e-01, 2.02809315e-04, 4.43527460e-06,
        2.79457981e-05, 2.26359975e-06, 1.84310829e-05, 8.40902270e-04,
        1.56515453e-04, 7.88022987e-07],
       [9.99805987e-01, 1.80888620e-07, 6.03628941e-05, 1.11560695e-07,
        1.45754041e-06, 7.00189730e-07, 4.89418562e-05, 7.05293205e-05,
        8.27773228e-09, 1.17776881e-05],
       [3.20452472e-07, 1.26853428e-09, 5.34800483e-06, 1.49605214e-07,
        9.92806017e-01, 5.37420476e-07, 3.66440190e-06, 9.54827701e-05,
        1.08385336e-06, 7.08738202e-03]], dtype=float32)>