In [2]:
# Import Required Libs
import numpy as np


array([[0.17419952, 0.00802682],
       [0.44295124, 0.86240045]])

In [9]:
X = np.random.rand(2,2)
X

array([[0.78801942, 0.93347279],
       [0.59933246, 0.38784936]])

In [7]:
U, S, V = np.linalg.svd(X, full_matrices=True)

#Economy SVD - For Non Square Matrices
U_hat, S_hat, V_hat = np.linalg.svd(X, full_matrices=False)

In [8]:
U

array([[-0.09128829, -0.99582451],
       [-0.99582451,  0.09128829]])