In [13]:
import tensorflow as tf
import matplotlib.pyplot as plt
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.7.0


In [15]:
mnist = tf.keras.datasets.mnist # MNIST Number datasets

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [16]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [17]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.14272025, -0.6830386 , -0.2861655 ,  0.29325938, -0.07455339,
         0.73134214, -0.37332496,  0.18949577,  1.0321953 , -0.06454566]],
      dtype=float32)

In [19]:
tf.nn.softmax(predictions).numpy()
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

1.786212

In [20]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [21]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
   1/1875 [..............................] - ETA: 5:35 - loss: 2.3016 - accuracy: 0.1250

2022-01-02 23:03:22.641942: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-01-02 23:03:22.738834: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


1875/1875 [==============================] - 9s 5ms/step - loss: 0.2941 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1413 - accuracy: 0.9584
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1051 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0835 - accuracy: 0.9744
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0700 - accuracy: 0.9777


In [22]:
model.evaluate(x_test,  y_test, verbose=2)

2022-01-02 23:04:11.132780: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


313/313 - 1s - loss: 0.0787 - accuracy: 0.9744 - 1s/epoch - 4ms/step


[0.07873234152793884, 0.9744000434875488]

In [23]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [24]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[4.22719992e-08, 7.85745371e-08, 2.22536946e-05, 1.83446950e-03,
        6.70054359e-11, 2.77003778e-07, 2.04675822e-13, 9.98125374e-01,
        1.53961923e-06, 1.59202900e-05],
       [1.19299068e-06, 3.61132443e-05, 9.99712586e-01, 2.43106246e-04,
        5.47469153e-11, 3.85930463e-07, 5.49170409e-07, 3.54378332e-10,
        6.13484417e-06, 1.91815357e-12],
       [1.63495201e-06, 9.99346077e-01, 2.54163053e-04, 3.57973317e-06,
        3.33260468e-05, 1.00517127e-06, 1.55852285e-05, 9.85473525e-05,
        2.45714560e-04, 5.21282573e-07],
       [9.99877930e-01, 4.14408036e-10, 2.28632252e-05, 2.13985771e-07,
        6.22592495e-07, 5.49413016e-06, 9.14209304e-05, 7.27934889e-07,
        1.17377450e-08, 7.63021774e-07],
       [7.92473543e-07, 1.16292549e-08, 1.01049795e-06, 1.23098459e-07,
        9.99602139e-01, 1.01205565e-07, 4.41725069e-06, 2.47615553e-05,
        1.21424227e-06, 3.65354790e-04]], dtype=float32)>